### ISSUE TITLE
how local variables between two function talk to each other

### ISSUE THREAD

**Issue by pragyes31** [pragyes31/calculator#2]
I have a displayNum function which relies on recordOps function to decide whether value should be assigned to firstNum variable or secondNum variable. How would the displayNum function read the value of operator value from the recordOps function?

``` javascript
function recordOps(eve) {
  let operator = "";
  operator = eve.target.innerHTML;
  console.log(operator);
}
function displayNum(display, eve) {
  let firstNum = "";
  let secondNum = "";
  let numberClicked = operator=== "" ? firstNum : secondNum;
}
```

**Comment by vramana** [comment]
One way to make functions communicate data is make as methods on a object 

```js
const a  = {
   b: 0,
   setFour: function () {
      b = 4;
   },
   print: function () {
      console.log(a.b)
   }
}

a.print(); // prints 0 
a.setFour();
a.print(); // prints 4 
``` 

Does that help?

**Comment by pragyes31** [comment]
yeah, it make sense. Let me try something like this. Thanks

**Comment by pragyes31** [comment]
It worked, thanks Ramana
